"""
CertiTrust AI - Employer Portal Verification Test Suite.
Tests the 6 employer verification workflows and granular change detection.
"""

import io
from fastapi.testclient import TestClient
from PIL import Image, ImageDraw, PngImagePlugin
from app.main import app
from app.services.registry_service import credential_registry
from tests.test_credential_gating import (
    create_resume_bytes,
    create_random_screenshot_bytes,
)


def create_mock_btech_bytes(
    name: str = "RISHANK TIWARI",
    cgpa: str = "6.76",
    randomize_noise: bool = False
) -> bytes:
    """
    Generates a dynamic B.Tech marksheet image with specified name and CGPA.
    Changing randomize_noise changes the file hash while keeping the content comparable.
    """
    cert = Image.new("RGB", (900, 1050), color=(255, 255, 255))
    draw = ImageDraw.Draw(cert)
    
    if randomize_noise:
        draw.line([0, 0, 10, 10], fill=(240, 240, 240))

    text_content = (
        "Parul University\n"
        "Statement of Marks/Grade\n"
        "Bachelor of Technology\n"
        "Bachelor of Technology in Computer Science and Engineering - Artificial Intelligence and Machine Learning\n"
        "II SEMESTER\n"
        "MAY 2026 Examination 2025-26\n"
        "APAAR ID: 676402918047\n"
        "Reg No.: 2503031460770\n"
        "Roll No.: AF21650\n"
        f"Name: {name}\n"
        "Father's Name: GAJENDRA TIWARI\n"
        "Mother's Name: BHAVNA SHARMA\n"
        "College/Department: PARUL INSTITUTE OF ENGINEERING & TECHNOLOGY (FIRST SHIFT)\n"
        "Category: REGULAR\n"
        "--------------------------------------------------\n"
        "S.No. Course ID Subject Grade GradePoints Credits CreditPoints\n"
        "1 03010002HM01 ADVANCED COMMUNICATION AND INTERPERSONAL SKILLS B 6 2 12\n"
        "2 03010002MC01 ENVIRONMENTAL SCIENCE B+ 7 0 0\n"
        "3 03010502ES01 OBJECTED ORIENTED PROGRAMMING B+ 7 3 21\n"
        "4 03010601ES02 ELECTRICAL AND ELECTRONICS ENGINEERING B 6 4 24\n"
        "5 03010702ES01 ICT WORKSHOP B+ 7 1 7\n"
        "6 03014602PC01 PYTHON PROGRAMMING B+ 7 4 28\n"
        "7 03019102BS01 LINEAR ALGEBRA B 6 4 24\n"
        "8 03M10002UE01 PRIVACY AND SECURITY IN ONLINE SOCIAL MEDIA B+ 7 3 21\n"
        "--------------------------------------------------\n"
        "TOTAL Credits: 21 Credit Points: 137\n"
        f"SGPA: 6.52 CGPA: {cgpa} Percentage: 61.44 RESULT: PASS\n"
        "Dated: 30/06/2026 Division: FIRST CLASS\n"
        "This is a digital certificate. The certificate is electronically generated by DigiLocker - National Academic Depository.\n"
        "Digitally signed on Date: 22/07/2026 20:53:39 IST\n"
    )
    draw.text((40, 40), text_content, fill=(0, 0, 0))
    meta = PngImagePlugin.PngInfo()
    meta.add_text("Comment", text_content)
    buf = io.BytesIO()
    cert.save(buf, format="PNG", pnginfo=meta)
    return buf.getvalue()


def test_employer_verification_workflow():
    client = TestClient(app)

    # 0. Initial Setup: Issuer registers the original B.Tech Marksheet
    credential_registry.clear()
    original_bytes = create_mock_btech_bytes()
    
    print("\n---------------------------------------------")
    print("Setup Step: Issuer Registers Original Reference Document")
    reg_res = client.post(
        "/api/v1/issuer/credentials",
        files={"certificate": ("original_btech.png", original_bytes, "image/png")}
    )
    assert reg_res.status_code == 201
    reg_data = reg_res.json()
    cred_id = reg_data["credential_id"]
    print("Registered Credential ID:", cred_id)

    # TEST 1: Upload the EXACT SAME file registered by the issuer
    print("\n---------------------------------------------")
    print("Test 1: Exact Same File Verification")
    res1 = client.post(
        "/api/v1/employer/verify",
        files={"certificate": ("candidate_btech_exact.png", original_bytes, "image/png")},
        data={"credential_id": cred_id}
    )
    assert res1.status_code == 200
    data1 = res1.json()
    print("status:", data1["verification_status"])
    print("risk_level:", data1["risk_level"])
    print("credential_match:", data1["credential_match"])
    print("hash_match:", data1["hash_match"])
    print("field_match_percentage:", data1["field_match_percentage"])
    print("changed_parameters_count:", data1["changed_parameters_count"])
    print("total_parameters_checked:", data1["total_parameters_checked"])

    assert data1["verification_status"] == "VERIFIED"
    assert data1["risk_level"] == "LOW"
    assert data1["credential_match"] is True
    assert data1["hash_match"] is True
    assert data1["field_match_percentage"] == 100.0
    assert data1["changed_parameters_count"] == 0

    # TEST 2: Content matches registered record, but file hash differs
    print("\n---------------------------------------------")
    print("Test 2: Match Content (Different Hash)")
    different_hash_bytes = create_mock_btech_bytes(randomize_noise=True)
    res2 = client.post(
        "/api/v1/employer/verify",
        files={"certificate": ("candidate_btech_diff_hash.png", different_hash_bytes, "image/png")},
        data={"credential_id": cred_id}
    )
    assert res2.status_code == 200
    data2 = res2.json()
    print("status:", data2["verification_status"])
    print("risk_level:", data2["risk_level"])
    assert data2["verification_status"] == "VERIFIED"
    assert data2["risk_level"] == "LOW"
    assert data2["credential_match"] is True
    assert data2["hash_match"] is False
    assert "hash differs" in data2["recommendation"].lower()

    # TEST 3: CGPA Mismatch (Discrepancy -> HIGH RISK)
    print("\n---------------------------------------------")
    print("Test 3: CGPA Mismatch Discrepancy")
    forged_cgpa_bytes = create_mock_btech_bytes(cgpa="9.76")
    res3 = client.post(
        "/api/v1/employer/verify",
        files={"certificate": ("forged_cgpa.png", forged_cgpa_bytes, "image/png")},
        data={"credential_id": cred_id}
    )
    assert res3.status_code == 200
    data3 = res3.json()
    print("status:", data3["verification_status"])
    print("risk_level:", data3["risk_level"])
    print("changed_parameters_count:", data3["changed_parameters_count"])
    print("changed_parameters_count:", len(data3["changed_parameters"]))

    assert data3["verification_status"] == "MISMATCH"
    assert data3["risk_level"] == "HIGH"
    assert data3["credential_match"] is False
    assert data3["changed_parameters_count"] == 1
    
    # Assert change structure values
    change = data3["changed_parameters"][0]
    assert change["field"] == "cgpa"
    assert change["status"] == "CHANGED"
    assert float(change["original_value"]) == 6.76
    assert float(change["submitted_value"]) == 9.76
    assert float(change["difference"]) == 3.0

    # TEST 4: Student Name Mismatch (Discrepancy -> HIGH RISK)
    print("\n---------------------------------------------")
    print("Test 4: Student Name Mismatch Discrepancy")
    forged_name_bytes = create_mock_btech_bytes(name="JOHN DOE")
    res4 = client.post(
        "/api/v1/employer/verify",
        files={"certificate": ("forged_name.png", forged_name_bytes, "image/png")},
        data={"credential_id": cred_id}
    )
    assert res4.status_code == 200
    data4 = res4.json()
    print("status:", data4["verification_status"])
    print("risk_level:", data4["risk_level"])
    print("changed_parameters_count:", len(data4["changed_parameters"]))

    assert data4["verification_status"] == "MISMATCH"
    assert data4["risk_level"] == "HIGH"
    assert data4["credential_match"] is False
    assert any(c["field"] == "student_name" and c["submitted_value"] == "JOHN DOE" for c in data4["changed_parameters"])

    # TEST 5: Legitimate Credential, but UNREGISTERED
    print("\n---------------------------------------------")
    print("Test 5: Unregistered Credential Lookup")
    credential_registry.clear()
    res5 = client.post(
        "/api/v1/employer/verify",
        files={"certificate": ("candidate_btech_unregistered.png", original_bytes, "image/png")},
        data={"credential_id": "CERT-2026-UNFOUND"}
    )
    assert res5.status_code == 200
    data5 = res5.json()
    print("status:", data5["verification_status"])
    print("risk_level:", data5["risk_level"])
    print("message:", data5["message"])

    assert data5["verification_status"] == "UNREGISTERED"
    assert data5["risk_level"] == "HIGH"
    assert data5["unverified_parameters_count"] > 0

    # TEST 6: Upload unrelated screenshot or CV (Gated -> stopped)
    print("\n---------------------------------------------")
    print("Test 6: Reject Resume/CV Verification")
    res6 = client.post(
        "/api/v1/employer/verify",
        files={"certificate": ("resume.png", create_resume_bytes(), "image/png")}
    )
    assert res6.status_code == 200
    data6 = res6.json()
    print("is_supported:", data6["is_supported"])
    print("verification_stopped:", data6.get("verification_stopped"))
    print("status:", data6.get("verification_status"))

    assert data6["is_supported"] is False
    assert data6.get("verification_stopped") is True
    assert data6.get("verification_status") == "REJECTED"

    print("\nALL EMPLOYER VERIFICATION PORTAL TESTS VERIFIED SUCCESSFULLY!")


if __name__ == "__main__":
    test_employer_verification_workflow()
